prod:
  stage: deploy
  only:
    - master

  before_script:
    - mkdir -m 777 -p ~/.ssh
    - echo -e "$PROD_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\t SrictHostKeyCheking no\n\n" > ~/.ssh/config'

  script:
    - bash .gitlab-deploy-prod.sh

  environment:
    name: production
    url : https://www.annual-project.com
