image: node:8.9.0

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - bash ls
  only:
    - master
